/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Calendar: typeof import('./components/component/calendar.vue')['default']
    CameraAccess: typeof import('./components/CameraAccess.vue')['default']
    Character: typeof import('./components/charcter/character.vue')['default']
    DressUpGame: typeof import('./components/DressUpGame.vue')['default']
    HelloWorld: typeof import('./components/login.vue')['default']
    Login: typeof import('./components/login.vue')['default']
    Navbar: typeof import('./components/component/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
